POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nowak",
  "email": "adam.nowak@gmail.com",
  "address": "Lublin, Racławickie",
  "password": "top secret",
  "creditCard": {
    "number": "123456",
    "holder": "Adam Nowak",
    "verificationCode": "123",
    "month": 1,
    "year": 2020
  }
}

###

GET http://localhost:8080/users/3
Accept: application/json

###